/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileUploadSessionIdRouteImport } from './routes/mobile-upload.$sessionId'
import { Route as ApiPublicHooksCleanupUploadsRouteImport } from './routes/api/public/hooks/cleanup-uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileUploadSessionIdRoute = MobileUploadSessionIdRouteImport.update({
  id: '/mobile-upload/$sessionId',
  path: '/mobile-upload/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupUploadsRoute =
  ApiPublicHooksCleanupUploadsRouteImport.update({
    id: '/api/public/hooks/cleanup-uploads',
    path: '/api/public/hooks/cleanup-uploads',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
  '/api/public/hooks/cleanup-uploads': typeof ApiPublicHooksCleanupUploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
  '/api/public/hooks/cleanup-uploads': typeof ApiPublicHooksCleanupUploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
  '/api/public/hooks/cleanup-uploads': typeof ApiPublicHooksCleanupUploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile-upload/$sessionId'
    | '/api/public/hooks/cleanup-uploads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mobile-upload/$sessionId' | '/api/public/hooks/cleanup-uploads'
  id:
    | '__root__'
    | '/'
    | '/mobile-upload/$sessionId'
    | '/api/public/hooks/cleanup-uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileUploadSessionIdRoute: typeof MobileUploadSessionIdRoute
  ApiPublicHooksCleanupUploadsRoute: typeof ApiPublicHooksCleanupUploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-upload/$sessionId': {
      id: '/mobile-upload/$sessionId'
      path: '/mobile-upload/$sessionId'
      fullPath: '/mobile-upload/$sessionId'
      preLoaderRoute: typeof MobileUploadSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-uploads': {
      id: '/api/public/hooks/cleanup-uploads'
      path: '/api/public/hooks/cleanup-uploads'
      fullPath: '/api/public/hooks/cleanup-uploads'
      preLoaderRoute: typeof ApiPublicHooksCleanupUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileUploadSessionIdRoute: MobileUploadSessionIdRoute,
  ApiPublicHooksCleanupUploadsRoute: ApiPublicHooksCleanupUploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
