/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileUploadSessionIdRouteImport } from './routes/mobile-upload.$sessionId'
import { Route as ApiDebugEnvRouteImport } from './routes/api/debug-env'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileUploadSessionIdRoute = MobileUploadSessionIdRouteImport.update({
  id: '/mobile-upload/$sessionId',
  path: '/mobile-upload/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEnvRoute = ApiDebugEnvRouteImport.update({
  id: '/api/debug-env',
  path: '/api/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/debug-env': typeof ApiDebugEnvRoute
  '/mobile-upload/$sessionId': typeof MobileUploadSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/debug-env' | '/mobile-upload/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/debug-env' | '/mobile-upload/$sessionId'
  id: '__root__' | '/' | '/api/debug-env' | '/mobile-upload/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDebugEnvRoute: typeof ApiDebugEnvRoute
  MobileUploadSessionIdRoute: typeof MobileUploadSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-upload/$sessionId': {
      id: '/mobile-upload/$sessionId'
      path: '/mobile-upload/$sessionId'
      fullPath: '/mobile-upload/$sessionId'
      preLoaderRoute: typeof MobileUploadSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-env': {
      id: '/api/debug-env'
      path: '/api/debug-env'
      fullPath: '/api/debug-env'
      preLoaderRoute: typeof ApiDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDebugEnvRoute: ApiDebugEnvRoute,
  MobileUploadSessionIdRoute: MobileUploadSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
